# Generated by Django 4.2.6 on 2023-12-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_No', models.IntegerField()),
                ('DName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EID', models.IntegerField()),
                ('Emp_Name', models.CharField(max_length=100, unique=True)),
                ('Job', models.CharField(max_length=100)),
                ('HireDate', models.DateField()),
                ('Commition', models.IntegerField()),
                ('Dept_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
